#!/bin/bash

SOURCE=gp_onDaughterCell-V10.cc
STEM=$(basename $SOURCE .cc)

g++ -w -g  -o $STEM $SOURCE gp_list.cpp randInsertTransposon.cpp

if [ $? = 0 ];then
   ./$STEM 
else
  echo error
fi

###################################
exit

